name: Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to remove AWS resources for?
        options:
          - staging
          - prod #allows prod to be turned off to save money in tutorial
jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout/@v4
      - name: Terraform Destroy
        env: 
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export TF_WORKSPACE=${{ github.event.inputs.environment }}
          cd infra/
          docker compose run --rm terraform -chdir/ init
          docker compose run --rm terraform -chdir/ destroy -auto-approve
