name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Username for Dockerhub auth"
      DOCKERHUB_TOKEN:
        required: true
        description: "Token for DockerHub auth"

jobs:
  python:
    name: Python
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Plython flake8
        run: docker compose run --rm app sh -c "flake8"

  terrafrom:
    name: Terrafrom
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terrafrom lint
        run: |
          cd infra/
          docker compose run --rm terrafrom -chdir=deploy/ init -backend=false
          docker compose run --rm terrafrom -chdir=setup/ init -backend=false
          docker compose run --rm terrafrom -chdir=deploy/ validate
          docker compose run --rm terrafrom -chdir=deploy/ fmt -check
          docker compose run --rm terrafrom -chdir=setup/ validate
          docker compose run --rm terrafrom -chdir=setup/ fmt -check
